SET SERVEROUTPUT ON

DECLARE
    MAX_N NUMBER(30);
    CURSOR TABLES_CURSOR IS 
        SELECT A.OBJECT_NAME AS TABLE_NAME, NVL(MIN(C.COLUMN_NAME),0) AS PK_COLUMN
        FROM ALL_OBJECTS A, ALL_CONS_COLUMNS C
        WHERE A.OBJECT_NAME = C.TABLE_NAME 
          AND A.OWNER = 'SYSTEM'
          AND A.OBJECT_TYPE = 'TABLE'
          AND C.CONSTRAINT_NAME IN (SELECT CONSTRAINT_NAME FROM ALL_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'P')
        GROUP BY(A.OBJECT_NAME) 
        HAVING MIN(C.COLUMN_NAME) NOT IN (SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE DATA_TYPE <> 'NUMBER'); 

    CURSOR SEQUENCE_NAME_CURSOR IS 
        SELECT SEQUENCE_NAME FROM USER_SEQUENCES;
BEGIN
    FOR SEQUENCE_NAME_RECORD IN SEQUENCE_NAME_CURSOR LOOP
        EXECUTE IMMEDIATE 'DROP SEQUENCE '||SEQUENCE_NAME_RECORD.SEQUENCE_NAME;
    END LOOP;      
            
    FOR T_RECORD IN TABLES_CURSOR LOOP
        EXECUTE IMMEDIATE '
        SELECT (NVL(MAX('||T_RECORD.PK_COLUMN||'),0)+1) 
        FROM SYSTEM.' || T_RECORD.TABLE_NAME
        INTO MAX_N;

        EXECUTE IMMEDIATE '
        CREATE SEQUENCE '||T_RECORD.TABLE_NAME||'_SEQ
        START WITH '||MAX_N||'
        MAXVALUE 999999999999999999999999999
        MINVALUE 1
        NOCYCLE
        CACHE 20
        NOORDER';

        EXECUTE IMMEDIATE '
        CREATE OR REPLACE TRIGGER '||T_RECORD.TABLE_NAME||'_TR
        BEFORE INSERT
        ON SYSTEM.'||T_RECORD.TABLE_NAME||'
        REFERENCING NEW AS NEW OLD AS OLD
        FOR EACH ROW
        BEGIN
          :NEW.'||T_RECORD.PK_COLUMN||' := '||T_RECORD.TABLE_NAME||'_SEQ.NEXTVAL;
        END;';
    END LOOP;             
END;
/

INSERT INTO EMP_EMPLOYEES (EMP_NAME, EMAIL, BASE_SALARY) VALUES ('Mahmoud', 'mahmoud@example.com', 6000);
INSERT INTO EMP_EMPLOYEES (EMP_NAME, EMAIL, BASE_SALARY) VALUES ('Ahmed', 'ahmed@company.com', 4500);
INSERT INTO EMP_EMPLOYEES (EMP_NAME, EMAIL, BASE_SALARY) VALUES ('Sara', 'sara@test.com', 5000);  

CREATE OR REPLACE PROCEDURE CALCULATE_SALES_COMMISSIONS AS
    CURSOR EMP_SALES_CURSOR IS
        SELECT EMP_ID, SUM(SALE_AMOUNT) AS TOTAL_SALES
        FROM EMP_SALES
        GROUP BY EMP_ID;
        
    V_COMM_PERCENT NUMBER(5,2);
    V_COMM_AMOUNT  NUMBER(12,2);
BEGIN
    DELETE FROM EMP_CALCULATED_COMMISSIONS;

    FOR R_EMP IN EMP_SALES_CURSOR LOOP
        V_COMM_PERCENT := 0;
        V_COMM_AMOUNT  := 0;

        BEGIN
            SELECT COMM_PERCENT 
            INTO V_COMM_PERCENT
            FROM EMP_COMM_RULES
            WHERE R_EMP.TOTAL_SALES BETWEEN MIN_AMOUNT AND MAX_AMOUNT;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                V_COMM_PERCENT := 0;
        END;

        V_COMM_AMOUNT := R_EMP.TOTAL_SALES * (V_COMM_PERCENT / 100);

        IF V_COMM_AMOUNT > 0 THEN
            INSERT INTO EMP_CALCULATED_COMMISSIONS (EMP_ID, COMM_AMOUNT, CALC_DATE)
            VALUES (R_EMP.EMP_ID, V_COMM_AMOUNT, SYSDATE);
        END IF;
    END LOOP;

    COMMIT;
END;
/

INSERT INTO EMP_COMM_RULES (RULE_ID, MIN_AMOUNT, MAX_AMOUNT, COMM_PERCENT) VALUES (1, 1, 5000, 2);
INSERT INTO EMP_COMM_RULES (RULE_ID, MIN_AMOUNT, MAX_AMOUNT, COMM_PERCENT) VALUES (2, 5001, 15000, 5);
INSERT INTO EMP_COMM_RULES (RULE_ID, MIN_AMOUNT, MAX_AMOUNT, COMM_PERCENT) VALUES (3, 15001, 100000, 10);

INSERT INTO EMP_SALES (EMP_ID, SALE_AMOUNT) VALUES (1, 3000);
INSERT INTO EMP_SALES (EMP_ID, SALE_AMOUNT) VALUES (1, 4000);
INSERT INTO EMP_SALES (EMP_ID, SALE_AMOUNT) VALUES (2, 20000);
INSERT INTO EMP_SALES (EMP_ID, SALE_AMOUNT) VALUES (3, 1500);

COMMIT;

EXEC CALCULATE_SALES_COMMISSIONS; 

SELECT * FROM EMP_CALCULATED_COMMISSIONS;